import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

import '../../core/theme/app_typography.dart';
import '../../core/theme/context_colors.dart';

/// Zuzu's three moments from the "A Day With Zuzu" storyboard.
enum ZuzuMoment {
  /// Nothing recorded yet today. Blinks, tilts, gestures at the journal.
  /// Loops quietly — it must never pull focus from the task list.
  invitation('zuzu_invitation.json', true),

  /// The first real completion of the day. Crouch, leap, two flaps, land.
  firstWin('zuzu_first_win.json', false),

  /// The last scheduled task is done. He looks at the list, bows, waves.
  dayComplete('zuzu_day_complete.json', false),

  /// Calm and eyes closed. Focus sessions, the rest banner, the Sunday
  /// review — the surfaces Master Ren held before he was retired. Plays
  /// behind a running countdown, so it stays almost still.
  meditate('zuzu_meditate.json', true),

  /// A slow, understanding nod for honest misses and comebacks.
  /// Deliberately carries no celebratory motion: a miss must never read
  /// as a win.
  nod('zuzu_nod.json', false);

  const ZuzuMoment(this.file, this.loops);
  final String file;
  final bool loops;

  String get asset => 'assets/lottie/$file';
}

/// Zuzu, the app's face, as a Lottie playback surface.
///
/// Mirrors [StreakFlame]'s drop-in contract: the JSON is generated by
/// `tools/build_zuzu_lottie.py`, and a missing or unparseable file degrades
/// to empty space of the right size rather than taking a screen down with
/// it. Layout never jumps.
///
/// **Reduced motion freezes rather than hides.** Every generated file is
/// authored so frame 0 is Zuzu standing neutral and readable, which is why
/// `animate: !still` is the correct behaviour here and why the surfaces
/// using this widget keep showing their message either way.
class ZuzuFigure extends StatelessWidget {
  final ZuzuMoment moment;
  final double size;

  /// Optional proverb, shown in a bubble above — carried over from the
  /// retired RenFigure so its call sites did not have to be restructured.
  final String? line;

  /// Fires when a one-shot finishes, so a caller can advance a sequence.
  /// Never fires for looping moments, or when motion is reduced.
  final VoidCallback? onComplete;

  const ZuzuFigure({
    super.key,
    required this.moment,
    this.size = 120,
    this.line,
    this.onComplete,
  });

  @override
  Widget build(BuildContext context) {
    final body = _figure(context);
    if (line == null) return body;
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Container(
          constraints: const BoxConstraints(maxWidth: 260),
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 9),
          decoration: BoxDecoration(
            color: context.appCardSurface,
            borderRadius: BorderRadius.circular(14),
            border: Border.all(color: context.appBorder),
          ),
          child: Text(
            line!,
            textAlign: TextAlign.center,
            style: AppTypography.caption.copyWith(
              fontStyle: FontStyle.italic,
              color: context.appTextSecondary,
            ),
          ),
        ),
        const SizedBox(height: 6),
        body,
      ],
    );
  }

  Widget _figure(BuildContext context) {
    final still = MediaQuery.of(context).disableAnimations;
    return SizedBox(
      width: size,
      height: size,
      child: Lottie.asset(
        moment.asset,
        fit: BoxFit.contain,
        repeat: moment.loops,
        animate: !still,
        onLoaded: onComplete == null || still || moment.loops
            ? null
            : (composition) {
                // Lottie has no completion callback, so time it off the
                // composition's own declared duration.
                Future<void>.delayed(composition.duration, () {
                  onComplete?.call();
                });
              },
        errorBuilder: (_, __, ___) => SizedBox(width: size, height: size),
      ),
    );
  }
}
